Repository Breakthrough-Energy/PostREISE, pull requests merged in 2021-04, with the labels that each got.

#254 docs: fix link to function in docsting
  postreise/plot/plot_bar_generation_vs_capacity.py
  postreise/plot/plot_heatmap.py
Labels: documentation

#256 scatter capacity vs curtailment
  postreise/plot/demo/pie_generation_vs_capacity_demo.ipynb
  postreise/plot/demo/plot_curtailment_time_series_demo.ipynb
  postreise/plot/demo/scatter_capacity_vs_capacity_factor_demo.ipynb
  postreise/plot/demo/scatter_capacity_vs_curtailment_demo.ipynb
  postreise/plot/plot_scatter_capacity_vs_curtailment.py
Labels: visualization

#262 bar generation stack plot
  postreise/plot/demo/plot_bar_generation_stack_demo.ipynb
  postreise/plot/plot_bar_generation_stack.py
  postreise/plot/tests/test_plot_bar_generation_stack.py
Labels: visualization

#276 generation stack plot bug fix
  postreise/analyze/time.py
  postreise/plot/plot_generation_ts_stack.py
Labels: bug

#278 ci: add coverage report to pytest
  .coveragerc
  .github/workflows/test.yml
  Pipfile
  Pipfile.lock
  pytest.ini
  requirements.txt
  tox.ini
Labels: dependencies
