Repository Breakthrough-Energy/PostREISE, pull requests merged in 2021-05, with the labels that each got.

#292 bar generation max vs actual vs min
  postreise/plot/demo/bar_generation_max_min_actual_demo.ipynb
  postreise/plot/plot_bar_generation_max_min_actual.py
Labels: visualization

#294 Rename plot_upgrades_map to plot_transmission_upgrades map
  postreise/plot/demo/transmission_upgrades_map_demo.ipynb
  postreise/plot/plot_transmission_upgrades_map.py
Labels: visualization

#295 bar renewable max vs profile vs actual
  postreise/plot/demo/bar_renewable_max_profile_actual_demo.ipynb
  postreise/plot/plot_bar_renewable_max_profile_actual.py
Labels: visualization

#296 Add logo and badges to README
  README.md
Labels: documentation

#297 Update dependencies
  Pipfile.lock
Labels: dependencies

#299 fix: correct bug where get_dcline_differences fails for DC lines connected to new buses
  postreise/analyze/transmission/upgrades.py
  postreise/plot/plot_transmission_upgrades_map.py
Labels: bug
