Repository Breakthrough-Energy/PostREISE, pull requests merged in 2021-03, with the labels that each got.

#233 Abstract grid model
  postreise/analyze/check.py
  postreise/analyze/demand.py
  postreise/analyze/generation/curtailment.py
  postreise/analyze/generation/emissions.py
  postreise/analyze/generation/summarize.py
  postreise/analyze/generation/tests/test_capacity_value.py
  postreise/analyze/generation/tests/test_curtailment.py
  postreise/analyze/generation/tests/test_emissions.py
  postreise/analyze/generation/tests/test_summarize.py
  postreise/analyze/helpers.py
  postreise/analyze/tests/test_demand.py
  postreise/analyze/tests/test_helpers.py
  postreise/plot/demo/emissions_map_demo.ipynb
  postreise/plot/plot_bar_generation_vs_capacity.py
  postreise/plot/plot_curtailment_ts.py
  postreise/plot/plot_energy_carbon_stack.py
  postreise/plot/plot_generation_ts_stack.py
  postreise/plot/plot_interconnection_map.py
  postreise/plot/plot_pie_generation_vs_capacity.py
Labels: grid

#248 docs: fix link to function in docstring
  postreise/plot/plot_bar_generation_vs_capacity.py
Labels: documentation

#251 scatter plot capacity vs capacity factor
  postreise/analyze/generation/capacity.py
  postreise/analyze/generation/tests/test_capacity.py
  postreise/analyze/tests/test_time.py
  postreise/analyze/time.py
  postreise/plot/demo/scatter_capacity_vs_capacity_factor.ipynb
  postreise/plot/plot_bar_generation_vs_capacity.py
  postreise/plot/plot_curtailment_ts.py
  postreise/plot/plot_generation_ts_stack.py
  postreise/plot/plot_pie_generation_vs_capacity.py
  postreise/plot/plot_scatter_capacity_vs_capacity_factor.py
Labels: visualization
