Repository Breakthrough-Energy/PostREISE, pull requests merged in 2022-08, with the labels that each got.

#349 Fix typo in argument to workflow trigger
  .github/workflows/release.yml
Labels: bug

#350 Add note and print statement to describe function's behavior
  postreise/analyze/generation/summarize.py
  postreise/analyze/generation/tests/test_summarize.py
Labels: documentation

#362 Improve test coverage for plotting function plot_bar_shortfall
  postreise/plot/plot_bar_shortfall.py
  postreise/plot/tests/test_plot_bar_shortfall.py
Labels: good first issue
